name: Build and Push Server Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: actions/tools/docker-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: actions/docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Downcase repository owner name
              run: |
                  echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: actions/docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  # Итоговый тег будет выглядеть как: ghcr.io/ваш-логин-github/имя-репозитория:latest
                  tags: |
                      ghcr.io/${{ env.REPO_OWNER }}/shreeemp:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
